name: brick

on:
  issues:
    types: [opened]

jobs:
  ai:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{ toJson(github) }}
    steps:

      - name: Set issue body as output
        id: issue-body
        run: |
          echo "::set-output name=body::${{ github.event.issue.body }}"

      - name: Replace newline characters
        id: replace-newlines
        run: |
          echo "::set-output name=body::$(echo "${{ steps.issue-body.outputs.body }}" | tr '\n' ' ')"

      - name: comment
        run: echo "PROMPT=${TITLE} ${{ steps.replace-newlines.outputs.body }}" >> "$GITHUB_ENV"
        env:
          TITLE: ${{ github.event.issue.title }}      

      - uses: builtwithai/askgpt@main
        id: generate-response
        env:
          KEY: ${{ secrets.KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          MODEL: ${{ secrets.MODEL }}
        with:
          prompt: '{"prompt": ["${{ env.PROMPT }}, respond in markdown format: "]}'
      - env:
          RESPONSE: ${{ steps.generate-response.outputs.response }}
        run: echo ok

      - name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.generate-response.outputs.response }}
